creator: dennyrwa
lang: id
locale: id_ID
themecolor: ffffff
company: pembuatanlapangan.com
url: https://pembuatanlapangan.com
siteurl: https://pembuatanlapangan.com
icon: /favicon.ico
logo: /images/logo-pembuatanlapangan.webp
alt-logo: Logo of pembuatanlapangan.com
post-image-amp: https://pembuatlapangan.com/images/pembuatlapangan-600x60.png
twitter:
facebook: https://web.facebook.com/ask.jagota
instagram: https://www.instagram.com/pembuat_lapangan_olahraga/
youtube: https://www.youtube.com/channel/UCdi8zPRnk0PARpPDbCFgsXg
copyright: © Copyright <strong>pembuatanlapangan.com</strong>. <br>All Rights Reserved and All the trademarks are the property of their respective owners
whatsapp-float-desktop: https://web.whatsapp.com/send?phone=6285259647778&text=Hallo, CS pembuatanlapangan.com
whatsapp-float-phone: whatsapp://send?text=Hallo, CS pembuatanlapangan.com!&phone=+6285259647778
exclude: [README.md]
email: andi@pembuatanlapangan.com
streetAddress: Jl. Raya Tulungagung - Trenggalek, Dsn. Krajan, RT 03 RW 02, Desa Jarakan, Kec. Gondang
postOfficeBoxNumber: 
addressLocality: Kabupaten Tulungagung
addressRegion: Jawa Timur
postalCode: 66263
addressCountry: Indonesia
telephone: 6285259647778
telephone-detail: 0852-5964-7778
whatsapp-api: https://api.whatsapp.com/send?text=Hallo%20CS%20pembuatanlapangan.com%0A(Nama)%0A(Alamat)%20&phone=6285259647778
fb_app_id:
DMCA: 
place_id : ChIJ60aeplkdeS4RrnwXJ4dc0Vc
id_pelacakan_ga: 
google-my-bussiness:
permalink: pretty
collections:
  data-slider-desktop:
    output: true
  data-slider-mobile:
    output: true
  data-product:
    output: true
    permalink: /:name/
  data-client:
    output: true
    permalink: /testimoni/:name/
  data-stok-lama:
    output: true
    permalink: /:name/